version: "0.2"
words:
  - armv
  - automodule
  - autoupdate
  - binstall
  - bndy
  - chrono
  - clippy
  - cooldown
  - docsrs
  - endfor
  - endgroup
  - endmacro
  - furo
  - Gitea
  - gitmodules
  - hustcer
  - manylinux
  - maturin
  - musllinux
  - nextest
  - nurfile
  - nushell
  - orhun
  - pipx
  - pkgs
  - pybind
  - pyclass
  - pyfunction
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - reqwest
  - rustc
  - rustdoc
  - rustup
  - sccache
  - sdist
  - serde
  - splitn
  - startswith
  - staticmethod
  - thiserror
  - timeit
  - topo
  - zizmor
ignorePaths:
  - .gitignore
  - tests/assets/**/*.json
