version: "0.2"
words:
  - autoupdate
  - binstall
  - bndy
  - chrono
  - clippy
  - docsrs
  - endfor
  - endgroup
  - endmacro
  - Gitea
  - gitmodules
  - hustcer
  - nextest
  - nurfile
  - nushell
  - orhun
  - pipx
  - pybind
  - reqwest
  - rustc
  - rustdoc
  - rustup
  - serde
  - splitn
  - startswith
  - thiserror
  - timeit
  - topo
  - zizmor
ignorePaths:
  - .gitignore
  - tests/assets/**/*.json
