from enum import Enum
from pathlib import Path
from typing import NamedTuple

class GitClient:
    def __init__(self) -> None: ...
    def is_pr_event(self) -> bool: ...
    def is_debug_enabled(self) -> bool: ...
    @property
    def event_name(self) -> str | None: ...
    def set_user_agent(self, user_agent: str) -> None: ...
    async def get_list_of_changed_files(
        self,
        file_filter: FileFilter,
        lines_changed_only: LinesChangedOnly,
        base_diff: str | None = None,
        ignore_index: bool = False,
    ) -> dict[str, FileDiffLines]: ...
    async def post_thread_comment(self, options: ThreadCommentOptions) -> None: ...
    def append_step_summary(self, comment: str) -> None: ...
    async def cull_pr_reviews(self, options: ReviewOptions) -> ReviewOptions: ...
    async def post_pr_review(self, options: ReviewOptions) -> None: ...
    def write_output_variables(
        self, output_variables: list[OutputVariable]
    ) -> None: ...
    def write_file_annotations(self, annotations: list[FileAnnotation]) -> None: ...
    @property
    def client_kind(self) -> str: ...

class OutputVariable:
    def __init__(self, name: str, value: str) -> None: ...
    def validate(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class AnnotationLevel(Enum):
    Debug = ...
    Notice = ...
    Warning = ...
    Error = ...

class FileAnnotation:
    def __init__(
        self,
        severity: AnnotationLevel,
        path: str,
        message: str,
        start_line: int | None = None,
        end_line: int | None = None,
        start_column: int | None = None,
        end_column: int | None = None,
        title: str | None = None,
    ) -> None: ...
    @property
    def severity(self) -> AnnotationLevel: ...
    @severity.setter
    def severity(self, val: AnnotationLevel) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, val: str) -> None: ...
    @property
    def message(self) -> str: ...
    @message.setter
    def message(self, val: str) -> None: ...
    @property
    def start_line(self) -> int | None: ...
    @start_line.setter
    def start_line(self, val: int | None) -> None: ...
    @property
    def end_line(self) -> int | None: ...
    @end_line.setter
    def end_line(self, val: int | None) -> None: ...
    @property
    def start_column(self) -> int | None: ...
    @start_column.setter
    def start_column(self, val: int | None) -> None: ...
    @property
    def end_column(self) -> int | None: ...
    @end_column.setter
    def end_column(self, val: int | None) -> None: ...
    @property
    def title(self) -> str | None: ...
    @title.setter
    def title(self, val: str | None) -> None: ...

class DiffHunkHeader(NamedTuple):
    old_start: int
    old_lines: int
    new_start: int
    new_lines: int

class FileDiffLines:
    def __init__(self) -> None: ...
    def is_hunk_in_diff(self, hunk: DiffHunkHeader) -> tuple[int, int] | None: ...
    def is_line_in_diff(self, line: int) -> bool: ...
    @property
    def added_lines(self) -> list[int]: ...
    @property
    def added_ranges(self) -> list[tuple[int, int]]: ...
    @property
    def diff_hunks(self) -> list[tuple[int, int]]: ...

class FileFilter:
    def __init__(
        self, ignore: list[str], extensions: list[str], log_scope: str | None = None
    ) -> None: ...
    def parse_submodules(self, manifest_path: str | Path | None = None) -> None: ...
    def is_file_in_list(self, file_path: str | Path, ignored: bool) -> bool: ...
    def is_file_ignored(self, file_path: str | Path) -> bool: ...
    def is_file_not_ignored(self, file_path: str | Path) -> bool: ...
    def is_qualified(self, file_path: str | Path) -> bool: ...
    def walk_dir(self, root_path: str | Path) -> set[str]: ...
    @property
    def extensions(self) -> set[str]: ...
    @property
    def ignored(self) -> set[str]: ...
    @property
    def not_ignored(self) -> set[str]: ...

class LinesChangedOnly(Enum):
    On = ...
    Off = ...
    Diff = ...

def parse_diff(
    diff: str,
    file_filter: FileFilter,
    lines_changed_only: LinesChangedOnly | None = None,
) -> dict[str, FileDiffLines]: ...

class ReviewAction(Enum):
    Approve = ...
    RequestChanges = ...
    Comment = ...

class ReviewComment:
    def __init__(
        self, path: str, comment: str, line_end: int, line_start: int | None = None
    ) -> None: ...
    @property
    def line_start(self) -> int | None: ...
    @line_start.setter
    def line_start(self, val: int | None) -> None: ...
    @property
    def line_end(self) -> int: ...
    @line_end.setter
    def line_end(self, val: int) -> None: ...
    @property
    def comment(self) -> str: ...
    @comment.setter
    def comment(self, val: str) -> None: ...
    @property
    def path(self) -> str: ...
    @path.setter
    def path(self, val: str) -> None: ...

class ReviewOptions:
    def __init__(
        self,
        comments: list[ReviewComment],
        action: ReviewAction | None = None,
        summary: str | None = None,
        marker: str | None = None,
        allow_draft: bool = False,
        allow_closed: bool = False,
        delete_review_comments: bool = False,
    ) -> None: ...
    @property
    def comments(self) -> list[ReviewComment]: ...
    @comments.setter
    def comments(self, val: list[ReviewComment]) -> None: ...
    @property
    def action(self) -> ReviewAction | None: ...
    @action.setter
    def action(self, val: ReviewAction) -> None: ...
    @property
    def summary(self) -> str | None: ...
    @summary.setter
    def summary(self, val: str) -> None: ...
    @property
    def marker(self) -> str: ...
    @marker.setter
    def marker(self, val: str) -> None: ...
    @property
    def allow_draft(self) -> bool: ...
    @allow_draft.setter
    def allow_draft(self, val: bool) -> None: ...
    @property
    def allow_closed(self) -> bool: ...
    @allow_closed.setter
    def allow_closed(self, val: bool) -> None: ...
    @property
    def delete_review_comments(self) -> bool: ...
    @delete_review_comments.setter
    def delete_review_comments(self, val: bool) -> None: ...

class CommentKind(Enum):
    Concerns = ...
    Lgtm = ...

class CommentPolicy(Enum):
    Anew = ...
    Update = ...

class ThreadCommentOptions:
    def __init__(
        self,
        policy: CommentPolicy | None = None,
        comment: str | None = None,
        kind: CommentKind | None = None,
        marker: str | None = None,
        no_lgtm: bool = False,
    ) -> None: ...
    @property
    def policy(self) -> CommentPolicy | None: ...
    @policy.setter
    def policy(self, val: CommentPolicy) -> None: ...
    @property
    def comment(self) -> str | None: ...
    @comment.setter
    def comment(self, val: str) -> None: ...
    @property
    def kind(self) -> CommentKind | None: ...
    @kind.setter
    def kind(self, val: CommentKind) -> None: ...
    @property
    def marker(self) -> str | None: ...
    @marker.setter
    def marker(self, val: str) -> None: ...
    @property
    def no_lgtm(self) -> bool: ...
    @no_lgtm.setter
    def no_lgtm(self, val: bool) -> None: ...
