# required minimum nextest version
nextest-version = "0.9.77"

[profile.default]
# A profile to run most tests, except tests that run longer than 10 seconds
default-filter = "all()"

# This will flag any test that runs longer than 10 seconds. Useful when writing new tests.
slow-timeout = "10s"

[profile.ci]
# This profile is intended to run in CI workflows.
# Locally, use default profile to skip the slow ones.

# This is all tests including slow ones.
default-filter = "all()"

# show which tests were skipped
status-level = "skip"

# show log output from each test
failure-output = "immediate-final"
success-output = "immediate"
